# Generated by Django 3.0.2 on 2020-01-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('webtoon_url', models.URLField()),
                ('thumb_src', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('webtoon_url', models.URLField()),
                ('thumb_src', models.URLField()),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.Webtoon')),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('cut_src', models.URLField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.Episode')),
            ],
        ),
    ]
